local_backend: true
backend:
  name: git-gateway
  branch: main
locale: pt
media_folder: src/assets/images
public_folder: ../../assets/images
collections:
  - name: products
    label: Produtos
    folder: src/content/products
    extension: md
    label_singular: Produto
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - widget: string
        name: title
        label: Título
        required: true
      - widget: string
        name: title_en
        label: Título (Inglês)
        required: true
      - widget: string
        name: title_es
        label: Título (Espanhol)
        required: true
      - widget: markdown
        name: body
        label: Descrição
        editor_components: &a1 []
        modes: &a2
          - rich_text
        required: true
      - widget: markdown
        name: body_en
        label: Descrição (Inglês)
        editor_components: *a1
        modes: *a2
        required: true
      - widget: markdown
        name: body_es
        label: Descrição (Espanhol)
        editor_components: *a1
        modes: *a2
        required: true
      - widget: list
        name: applications
        label: Aplicações
        allow_add: true
        label_singular: Aplicação
        required: true
      - widget: list
        name: applications_en
        label: Aplicações (Inglês)
        allow_add: true
        label_singular: Aplicação
        required: true
      - widget: list
        name: applications_es
        label: Aplicações (Espanhol)
        allow_add: true
        label_singular: Aplicação
        required: true
      - widget: number
        name: position
        label: Posição
        min: 1
        default: 100
      - widget: string
        name: youtube
        label: Link do Youtube (pode ser apenas o ID)
        required: false
      - widget: image
        name: images
        allow_multiple: true
        label: Imagens
        required: true
        media_library:
          config:
            multiple: true
      - widget: list
        name: subproducts
        label: Subprodutos
        allow_add: true
        label_singular: Subproduto
        required: false
        fields:
          - widget: string
            name: title
            label: Título
            required: true
          - widget: string
            name: title_en
            label: Título (Inglês)
            required: true
          - widget: string
            name: title_es
            label: Título (Espanhol)
            required: true
          - widget: image
            name: images
            label: Imagems
            required: true
            allow_multiple: true
            media_library:
              config:
                multiple: true
  - name: pages
    label: Configuração das páginas
    files:
      - name: home
        label: Página inicial
        file: src/content/home/index.md
        delete: false
        extension: md
        editor:
          preview: false
        fields:
          - widget: markdown
            name: title
            label: Título
            editor_components: &a3 []
            modes: &a4
              - rich_text
            required: true
          - widget: markdown
            name: title_en
            label: Título (Inglês)
            editor_components: *a3
            modes: *a4
            required: true
          - widget: markdown
            name: title_es
            label: Título (Espanhol)
            editor_components: *a3
            modes: *a4
            required: true
          - widget: image
            name: titleBackground
            label: Imagem de fundo do título
            required: true
            allow_multiple: false
          - widget: markdown
            name: description
            label: Descrição
            editor_components: &a5 []
            modes: &a6
              - rich_text
            required: true
          - widget: markdown
            name: description_en
            label: Descrição (Inglês)
            editor_components: *a5
            modes: *a6
            required: true
          - widget: markdown
            name: description_es
            label: Descrição (Espanhol)
            editor_components: *a5
            modes: *a6
            required: true
          - widget: image
            name: descriptionBackgrounds
            label: Imagem da descrição
            required: true
            allow_multiple: true
            media_library:
              config:
                multiple: true
          - widget: markdown
            name: clients
            label: Clientes
            editor_components: &a7 []
            modes: &a8
              - rich_text
            required: true
          - widget: markdown
            name: clients_en
            label: Clientes (Inglês)
            editor_components: *a7
            modes: *a8
            required: true
          - widget: markdown
            name: clients_es
            label: Clientes (Espanhol)
            editor_components: *a7
            modes: *a8
            required: true
          - widget: image
            name: images
            allow_multiple: true
            label: Logo dos clients
            media_library:
              config:
                multiple: true
      - name: about
        label: Página sobre
        file: src/content/about/index.md
        delete: false
        extension: md
        editor:
          preview: false
        fields:
          - widget: markdown
            name: title
            label: Título
            editor_components: &a9 []
            modes: &a10
              - rich_text
            required: true
          - widget: markdown
            name: title_en
            label: Título (Inglês)
            editor_components: *a9
            modes: *a10
            required: true
          - widget: markdown
            name: title_es
            label: Título (Espanhol)
            editor_components: *a9
            modes: *a10
            required: true
          - widget: image
            name: titleBackground
            label: Imagem de fundo do título
            required: true
            allow_multiple: false
          - widget: markdown
            name: description
            label: Descrição
            editor_components: &a11 []
            modes: &a12
              - rich_text
            required: true
          - widget: markdown
            name: description_en
            label: Descrição (Inglês)
            editor_components: *a11
            modes: *a12
            required: true
          - widget: markdown
            name: description_es
            label: Descrição (Espanhol)
            editor_components: *a11
            modes: *a12
            required: true
          - widget: markdown
            name: mission
            label: Missão
            editor_components: &a13 []
            modes: &a14
              - rich_text
            required: true
          - widget: markdown
            name: mission_en
            label: Missão (Inglês)
            editor_components: *a13
            modes: *a14
            required: true
          - widget: markdown
            name: mission_es
            label: Missão (Espanhol)
            editor_components: *a13
            modes: *a14
            required: true
          - widget: markdown
            name: vision
            label: Visão
            editor_components: &a15 []
            modes: &a16
              - rich_text
            required: true
          - widget: markdown
            name: vision_en
            label: Visão (Inglês)
            editor_components: *a15
            modes: *a16
            required: true
          - widget: markdown
            name: vision_es
            label: Visão (Espanhol)
            editor_components: *a15
            modes: *a16
            required: true
          - widget: markdown
            name: values
            label: Valores
            editor_components: &a17 []
            modes: &a18
              - rich_text
            required: true
          - widget: markdown
            name: values_en
            label: Valores (Inglês)
            editor_components: *a17
            modes: *a18
            required: true
          - widget: markdown
            name: values_es
            label: Valores (Espanhol)
            editor_components: *a17
            modes: *a18
            required: true
          - widget: markdown
            name: dna
            label: Nosso DNA
            editor_components: &a19 []
            modes: &a20
              - rich_text
            required: true
          - widget: markdown
            name: dna_en
            label: Nosso DNA (Inglês)
            editor_components: *a19
            modes: *a20
            required: true
          - widget: markdown
            name: dna_es
            label: Nosso DNA (Espanhol)
            editor_components: *a19
            modes: *a20
            required: true
          - widget: list
            name: dnas
            label: DNAs
            allow_add: true
            max: 5
            min: 5
            fields:
              - widget: string
                name: title
                label: Título
                required: true
              - widget: string
                name: title_en
                label: Título (Inglês)
                required: true
              - widget: string
                name: title_es
                label: Título (Espanhol)
                required: true
              - widget: image
                name: image
                label: Imagem
                required: true
                allow_multiple: false
  - name: config
    label: Configurações gerais
    files:
      - name: config
        label: Configurações gerais
        file: src/content/config/index.md
        editor:
          preview: false
        extension: md
        fields:
          - widget: string
            name: email
            label: Email
            required: true
          - widget: string
            name: phone
            label: Telefone
            required: true
          - widget: object
            name: whatsapp
            label: Whatsapp
            required: true
            fields:
              - widget: string
                name: number
                label: Número
                required: true
              - widget: string
                name: message
                label: Mensagem
                required: true
          - widget: object
            name: address
            label: Endereço
            fields:
              - widget: string
                name: address
                label: Endereço
                required: true
              - widget: string
                name: maps
                label: Link do Google Maps
                required: true
          - widget: object
            name: instagram
            label: Instagram
            required: true
            fields:
              - widget: string
                name: url
                label: URL
                required: true
              - widget: string
                name: arroba
                label: Arroba
                required: true
          - widget: object
            name: facebook
            label: Facebook
            required: true
            fields:
              - widget: string
                name: url
                label: URL
                required: true
              - widget: string
                name: arroba
                label: Arroba
                required: true
          - widget: object
            name: linkedin
            label: Linkedin
            fields:
              - widget: string
                name: url
                label: URL
                required: true
              - widget: string
                name: arroba
                label: Arroba
                required: true
